name: Build and deploy Node.js app to Azure Web App - OJfrontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd FrontEnd/onlineJudge
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: FrontEnd/onlineJudge/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: List files in current directory
        run: ls -la

      - name: List node-app folder if exists
        run: ls -la node-app || echo 'node-app folder does not exist'

      - name: List dist folder if exists
        run: ls -la dist || echo 'dist folder does not exist'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CDB799B57F9E4FE99BA3EB284B75CE5E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FEB07AFC5ED14C338829C5490025D2BF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BBB09C6C7F1946F0A6CA3ED6A6C40111 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'OJfrontend'
          slot-name: 'Production'
          package: '.'





